---
services:
  nginx:
    build:
      context: .
    ports:
      - 80:80
    environment:
      CONFIG: |
        events {}
        http {
            server {
                listen 80;
                location / { return 200 'Hello, World'; }
            }
        }
